### ISSUE TITLE
Problem setting PATHs; Cannot find CUDA

### ISSUE THREAD

**Issue by jpchen** [BachiLi/redner#17]
Hi, i'm trying to install redner by following the directions in the readme.  after (painstakingly) installing all the dependencies, i tried running:
```
build git:(master) ✗ CUDA_INCLUDE_DIRS=/usr/local/cuda-10.0/include cmake ..

-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found suitable version "10.0", minimum required is "10")
CMake Warning (dev) at embree/common/cmake/test.cmake:31 (SET):
  implicitly converting 'INT' to 'STRING' type.
Call Stack (most recent call first):
  embree/CMakeLists.txt:93 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at embree/common/cmake/ispc.cmake:71 (SET):
  implicitly converting 'INT' to 'STRING' type.
Call Stack (most recent call first):
  embree/CMakeLists.txt:396 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- OpenImageIO not found in your environment. You can 1) install
                              via your OS package manager, or 2) install it
                              somewhere on your machine and point OPENIMAGEIO_ROOT to it. (missing: OPENIMAGEIO_INCLUDE_DIR OPENIMAGEIO_LIBRARY)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EMBREE_INCLUDE_PATH
   used as include directory in directory /home/jpchen/3d-scene-gen/path_tracer/redner
   ...
EMBREE_LIBRARY
    linked by target "redner" in directory /home/jpchen/3d-scene-gen/path_tracer/redner
THRUST_INCLUDE_DIR
   used as include directory in directory /home/jpchen/3d-scene-gen/path_tracer/redner
```
And my build is failing (presumably due to other reasons).  From the error logs:
<details>
  <summary>Error log</summary>

  ```
Determining if the pthread_kill exist failed with the following output:
Change Dir: /home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_429d1/fast
/usr/bin/make -f CMakeFiles/cmTC_429d1.dir/build.make CMakeFiles/cmTC_429d1.dir/build
make[1]: Entering directory '/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_429d1.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_429d1.dir/CheckSymbolExists.c.o   -c /home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘pthread_kill’ undeclared (first use in this function)
   return ((int*)(&pthread_kill))[argc];
                   ^
/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/cmTC_429d1.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_429d1.dir/CheckSymbolExists.c.o' failed
make[1]: *** [CMakeFiles/cmTC_429d1.dir/CheckSymbolExists.c.o] Error 1
make[1]: Leaving directory '/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_429d1/fast' failed
make: *** [cmTC_429d1/fast] Error 2

File /home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_kill
  return ((int*)(&pthread_kill))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_31319/fast
/usr/bin/make -f CMakeFiles/cmTC_31319.dir/build.make CMakeFiles/cmTC_31319.dir/build
make[1]: Entering directory '/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_31319.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_31319.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.14/Modules/CheckFunctionExists.c
Linking C executable cmTC_31319
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_31319.dir/link.txt --verbose=1
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_31319.dir/CheckFunctionExists.c.o  -o cmTC_31319 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_31319.dir/build.make:86: recipe for target 'cmTC_31319' failed
make[1]: *** [cmTC_31319] Error 1
make[1]: Leaving directory '/home/jpchen/3d-scene-gen/path_tracer/redner/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_31319/fast' failed
make: *** [cmTC_31319/fast] Error 2
  ```
</details>

specs:
```
build git:(master) ✗ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

build git:(master) ✗ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```
and i am using conda with python 3.

and when i set paths such as `EMBREE_INCLUDE_PATH` etc, i still get the error that they are not found.  am i setting paths correctly?  could you give an example path or which directories the paths should point to?

**Comment by HectorAnadon** [comment]
[This](https://github.com/BachiLi/redner/issues/6) might be useful but I don't know if it will solve your problems. 
This is how set the paths in the CMake file:
`set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda")
set(OptiX_INCLUDE "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/include")
set(optix_LIBRARY "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix.so")
set(optix_prime_LIBRARY "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1")
set(EMBREE_LIBRARY "/home/hleon/Downloads/embree-3.2.4.x86_64.linux/lib/libembree3.so.3")
set(EMBREE_INCLUDE_PATH "/home/hleon/Downloads/embree-3.2.4.x86_64.linux/include/")`

And for running, I export this environmental variables:
`export PATH=/usr/local/cuda-10.0/bin:$PATH
source /home/hleon/Downloads/embree-3.2.4.x86_64.linux/embree-vars.sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64:/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64`

**Comment by BachiLi** [comment]
Can you provide a more complete log? In particular I would like to know which dependency is making CMake to check for pthread

**Comment by BachiLi** [comment]
also another alternative for setting cmake paths is cmake -D...=...

**Comment by jpchen** [comment]
sorry for the delayed response; i tried a few  different things to no avail.
@HectorAnadon  where exactly am i supposed to be setting the path? no matter where i put the `set` commands above i still get the error message that all the paths are missing.
@BachiLi i updated the OP with the complete error log.  since OpenEXR, and embree were included as submodules in this repo, i installed them from from source (from the git repo).  thrust comes with my cuda10 installation.  any help would be much appreciated.

**Comment by HectorAnadon** [comment]
I set the paths just it below
`set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")`
My LD_LIBRARY_PATH looks like this:
`LD_LIBRARY_PATH=/home/hleon/Downloads/embree-3.2.4.x86_64.linux/lib::/usr/local/cuda-10.0/lib64:/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64`

**Comment by jpchen** [comment]
i tried putting it in the cmake file or CmakeList but it gets ignored. i was able to get it to work using @BachiLi's suggestion of `cmake -D[name]=[path]`.  however i now have a curious behavior where `make install` fails with both gcc5 and gcc7, but if run it with gcc5 first (which fails) then run `make install` again with gcc7, it builds successfully (due to caching or .o files...?), but i am not convinced it is a good install since even though i can import it, i get errors when i run any example (#20).  anyone come across this issue?

**Comment by BachiLi** [comment]
I don't know what's wrong with gcc5, but the gcc7 error you post seems to be from a bug in the CUDA compiler. I did run into this occasionally and some of this seems to come from the assertions I added. I pushed something that remove some assertions. Can you try again with the latest commit?

**Comment by jpchen** [comment]
same error :(.  in order, the complete set of commands i'm running are:
```
source embree-vars.sh
export PATH=...
export EMBREE_INCLUDE_PATH=...
export LD_LIBRARY_PATH=...
mkdir build; cd build
cmake -DCUDA_INCLUDE_DIRS=/usr/local/cuda-10.0/include -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DCUDA_CUDART_LIBRARY=/usr/local/cuda-10.0/lib64 \
-DEMBREE_LIBRARY=[...]/embree/build/libembree3.so.3.4.0 -DEMBREE_INCLUDE_PATH=[...]/embree/include -DTHRUST_INCLUDE_DIR=/usr/local/cuda-10.0/include/thrust \
-DOptiX_INCLUDE=[...]/NVIDIA-OptiX-SDK-6.0.0-linux64/include -Doptix_LIBRARY=[...]/NVIDIA-OptiX-SDK-6.0.0-linux64/lib64/liboptix.so \
-Doptix_prime_LIBRARY=[...]/NVIDIA-OptiX-SDK-6.0.0-linux64/lib64/liboptix_prime.so ..
# where [...] are the absolute paths and there is a warning that THRUST_INCLUDE_DIR was not used
make install   # fails with error above
```

**Comment by jpchen** [comment]
@HectorAnadon would you mind sharing what version of OpenEXR and OpenEXR python you are using? i rolled everything back the the versions you have above yet am still getting `RuntimeError: Invalid context` when running any tutorial or example.

**Comment by LongruiDong** [comment]
> [This](https://github.com/BachiLi/redner/issues/6) might be useful but I don't know if it will solve your problems.
> This is how set the paths in the CMake file:
> 
> ```
> set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda")
> set(OptiX_INCLUDE "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/include")
> set(optix_LIBRARY "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix.so")
> set(optix_prime_LIBRARY "/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1")
> set(EMBREE_LIBRARY "/home/hleon/Downloads/embree-3.2.4.x86_64.linux/lib/libembree3.so.3")
> set(EMBREE_INCLUDE_PATH "/home/hleon/Downloads/embree-3.2.4.x86_64.linux/include/")
> ```
> 
> And for running, I export this environmental variables:
> 
> ```
> export PATH=/usr/local/cuda-10.0/bin:$PATH
> source /home/hleon/Downloads/embree-3.2.4.x86_64.linux/embree-vars.sh
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64:/home/hleon/Downloads/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64
> ```

yeah it worked for me ~
Thanks~~
